# Generated by Django 3.0.3 on 2020-02-27 10:53

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.image_file_path),
        ),
    ]
